markdown: rdiscount
permalink: /:title/
url: http://codebook.github.io/
name: Lowry's Home
author: Lowry
duoshuo: codebook
email: lrj.priv#gmail.com
github: codebook
highlighter: pygments
safe: true
paginate: 20
about: "Lowry 的个人博客<br /><br />"
